[package]
name = "stackable-zookeeper-crd"
version = "0.1.0"
authors = ["Lars Francke <lars.francke@stackable.de>"]
edition = "2018"

[dependencies]
k8s-openapi = { version = "0.9.0", default-features = false, features = ["v1_18"] } # 1.19 and k8s-openapi 0.10 are not supported in kube 0.43 yet, they will be in the next released version
kube = { version = "0.43", default-features = false, features = ["derive", "native-tls"] } # TODO: native-tls needs to go later and this crate needs to offer features itself
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
thiserror = "1.0"
tracing = "0.1"
