[package]
name = "stackable-zookeeper-operator"
version = "0.1.0"
authors = ["Lars Francke <lars.francke@stackable.de>"]
edition = "2018"

[[bin]]
doc = false
name = "controller"
path = "src/main.rs"

[lib]
name = "controller"
path = "src/lib.rs"

[dependencies]
actix-web = "3.2"
futures = "0.3"
k8s-openapi = { version = "0.9.0", default-features = false, features = ["v1_18"] } # 1.19 and k8s-openapi 0.10 are not supported in kube 0.43 yet, they will be in the next released version
kube = { version = "0.43", default-features = false, features = ["derive"] }
kube-runtime = "0.43.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "0.2", features = ["macros"] }

chrono = { version = "0.4.15", features = ["serde"] }
color-eyre = "0.5.2"
prometheus = "0.10.0"
snafu = "0.6.8"
tracing = "0.1.19"
tracing-futures = "0.2.4"
tracing-subscriber = "0.2.11"
