[package]
name = "stackable-zookeeper-operator-server"
version = "0.1.0"
authors = ["Lars Francke <lars.francke@stackable.de>"]
edition = "2018"

[dependencies]
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git" }
stackable-zookeeper-crd = { path = "../crd" }
stackable-zookeeper-operator = { path = "../operator" }

tokio = { version = "0.2", features = ["macros", "rt-threaded"] }
