[package]
name = "stackable-zookeeper-operator-server"
version = "0.1.0"
authors = ["Lars Francke <lars.francke@stackable.de>"]
edition = "2018"

[dependencies]
stackable-zookeeper-crd = { path = "../crd" }
stackable-zookeeper-operator = { path = "../operator" }

futures = "0.3"
k8s-openapi = { version = "0.9.0", default-features = false, features = ["v1_18"] } # 1.19 and k8s-openapi 0.10 are not supported in kube 0.43 yet, they will be in the next released version
kube = { version = "0.43", default-features = false, features = ["derive"] }
kube-runtime = "0.43.0"
thiserror = "1.0"
tokio = { version = "0.2", features = ["macros", "rt-threaded"] }
tracing = "0.1.19"
tracing-subscriber = "0.2.11"
